name: Run Divergebot
on:
  #  schedule:
  #    - cron: */5 * * * *
  workflow_dispatch:
    inputs:
      slack_webhook_url: # id of input
        description: "Slack webhook url for outgoing notifications"
        required: true

jobs:
  divergebot:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running divergebot"
      - uses: afiore/divergebot@v0.5.0
        with:
          slack_webhook_url: ${{ github.event.inputs.slack_webhook_url }}
          branches_to_compare: '["main...release/other"]'
          github_api_token: ${{ secrets.GITHUB_TOKEN }}
          github_owner_repo: ${{ env.GITHUB_REPOSITORY }}
